on: 
  release:
    types: [published]

jobs:
  release-latest-tag:
    name: Release Latest Tag
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest release
      uses: actions/checkout@v3
      with :
        ref: ${{ env.GITHUB_SHA }}
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: ronde-de-l-espoir.fr
        username: ctzs1179
        password: ${{ secrets.password }}
        server-dir: /ronde-de-l-espoir.fr/paiement/
